version: '3.7'
services:
    adminer:
        image: adminer
        restart: always
        ports:
          - 3333:3333

    web:
        image: nginx:latest
        ports:
            - 3310:3310
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./app:/app

    php:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./app:/app
    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'secret'
            MYSQL_USER: 'tutorial'
            MYSQL_PASSWORD: 'secret'
            MYSQL_DATABASE: 'tutorial'
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - 3306:3306
volumes:
    mysqldata: {}
